### PR TITLE
Refactor mergedate settings and authoryear citations

### PR DESCRIPTION
**Pull request by moewew**
Cf. #520 (see also #148).

Currently mergedate is still slightly broken and the format between citations and bibliography differs in year labels. This refactor brings bibliography and citations in line by using the same commands and fixes most of mergedate's fixable behaviour.

We simply use `\printlabeldateextra` in citations, this greatly reduces clutter.

### CODE REVIEW

**Comment by moewew** [comment]
Note that this is quite a large change. In my tests there were some differences in output compared to v3.7, but all of these were desirable as far as I can tell (and as far as I am concerned). I assume the test suite will also report different output, so that needs careful inspection.

**Comment by plk** [comment]
Just ran the test suite and am checking output now.

**Comment by plk** [comment]
First thing to note is the changed bibtex output where there seems to be repeated labelyear (from 01-introduction.tex):

screen shot 2017-08-06 at 5 00 pm

**Comment by moewew** [comment]
Ah, OK I will have to have a look at BibTeX. The tests are based on `labeldatesource` which is much safer than just comparing labelyear and year with Biber, but I didn't think about BibTeX.

**Comment by moewew** [comment]
If you can list all the other problems that arise I will have a look at those as well.

**Comment by plk** [comment]
The only other difference I see for the biber tests is that entries with month/day in the .bib always have this now in the bibliography - I'm not sure about this:

screen shot 2017-08-06 at 5 20 pm

**Comment by moewew** [comment]
This is my interpretation of what mergedate should do now. Previously entries like this would only have the month in the bibliography with the default `mergedate=compact` (this is the documented behaviour of mergedate in `50-style-authoryear`), but since we allow for days now we might as well include them.

The BibTeX problem could be solved by adding `labeldatesource` to the `.bbl`. I am currently trying to modify the `.bst` to do so. But I am quite clueless with `.bst` files, so if you have an idea...

**Comment by plk** [comment]
Ok, yes, I think you are right. In that case, the biber test files look good - great work, many thanks. @josephwright - you are the bibtex expert here - can you help? We really would like to fix this soon so we can release.

**Comment by moewew** [comment]
My attempt is at https://github.com/moewew/biblatex/commit/745596b90325f15cbc18cbb0183ef461d6d743cd

This adds `labeldatesource` with value `year` if labelyear is requested and we have a year.

**Comment by moewew** [comment]
I also had to modify `labelendyear`, see https://github.com/moewew/biblatex/commit/ffab5a5a3851a34602c59443e3a3cc952d0e7699

**Comment by moewew** [comment]
My suggested changes to `biblatex.bst` are in #606 now. It seems to work alright, but I would really appreciate someone with experience with BST files having a look.

**Comment by plk** [comment]
Tests look good, I have committed the test changes and uploaded a new 3.8. Seems we are close to being able to release?

**Comment by moewew** [comment]
Yes, but there are a few open issues left.
- #601 would be nice to have fixed before a release.
- I didn't get any further with #594, so unless you have an idea that would have to be deferred.
- #598, #586, #559 I'm clueless about and they are only 'small things', but can be _really_ annoying when noticed.
- #581 could hopefully be solved easily by someone who knows about `beamer`.
There is also #544 with `beamer` interaction.
- Regarding the date issue #540 is still open, and maybe John finds some quirks in the solution to #520 just committed.
- Not sure how we left #568.
- For weird punctuation problems there is #514 (we probably need to change the spacefactor of the ellipsis here) and #499.
- And #470 just crept up again.
- Also #585 was more complicated than I thought - mainly conceptually.

Of course that is just the list of issues that caught my eye when scrolling down the tracker.
#587 and #518 can easily be deferred.

**Comment by plk** [comment]
@moewew, @josephwright - can we clean up the last few things soon - we really should release I think - it's a bit overdue.

**Comment by moewew** [comment]
I think I could live with some of these things being deferred to the next version.
I started working on #585 and #514 and have at least a first attempt working. In #585 I would appreciate your feedback and ideally also Ulrike's response. In #514 I probably need Joseph to have a look.

**Pull request merged**
