### PR TITLE
Abstract key-val interface

### PR DESCRIPTION
**Pull request by moewew**
This should make it easier to switch to a different keyval package than `keyval` (something category stable that doesn't break with Turkish) in the future.

We use `\provide...` (or equivalent constructs) to overwrite existing definitions of `\blx@kv@...` which means users can define their own replacements before loading `biblatex`.

@Skillmon may for example want to use `expkv` with `biblatex`:
```latex
\documentclass[turkish]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}


\usepackage{expkv}
\makeatletter
% define a new key (possibly with a default value)
% {<family>}{<key>}[<default>]{<code>}
\newcommand*{\blx@kv@defkey}[2]{%
  \@ifnextchar[%
    {\blx@kv@defkey@default{#1}{#2}}
    {\blx@kv@defkey@nodefault{#1}{#2}}}

\def\blx@kv@defkey@nodefault{\ekvdef}
\def\blx@kv@defkey@default#1#2[#3]#4{%
  \csdef{blx@opthelper@#1@#2}##1{#4}%
  \ekvdef{#1}{#2}{\csuse{blx@opthelper@#1@#2}{##1}}%
  \ekvdefNoVal{#1}{#2}{\csuse{blx@opthelper@#1@#2}{#3}}}

% globally define new key (should only be the last resort)
% {<family>}{<key>}[<default>]{<code>}
\newcommand*{\blx@kv@gdefkey}[2]{%
  \@ifnextchar[%
    {\blx@kv@gdefkey@default{#1}{#2}}
    {\blx@kv@gdefkey@nodefault{#1}{#2}}}

\def\blx@kv@gdefkey@nodefault{\global\ekvdef}
\def\blx@kv@gdefkey@default#1#2[#3]#4{%
  \csgdef{blx@opthelper@#1@#2}##1{#4}%
  \global\ekvdef{#1}{#2}{\csuse{blx@opthelper@#1@#2}{##1}}%
  \global\ekvdefNoVal{#1}{#2}{\csuse{blx@opthelper@#1@#2}{#3}}}

% test if key is undefined
% {<family>}{<key>}{<true>}{<false>}
\newcommand*{\blx@kv@ifkeyundef}[2]{%
  \ekvifdefined{#1}{#2}
    {\@secondoftwo}
    {\@firstoftwo}}

% undefine key
% {<family>}{<key>}
\newcommand*{\blx@kv@undef}[2]{\csundef{\ekv@name{#1}{#2}}}
 
% {<family>}{<key-vals>}
\newcommand*{\blx@kv@setkeys}{\ekvset}
\makeatother
\usepackage[style=authoryear, backend=biber]{biblatex}

\addbibresource{biblatex-examples.bib}

\begin{document}
\cite{sigfridsson}
\printbibliography
\end{document}
```

### CODE REVIEW

**Comment by plk** [comment]
@moewew - running tests after this (and the previous index wrappers commit), I get some differences in 20,21,22 and 31 test files. Attached is screenshot diff of the first differences in 20 - some indices are missing?

Screenshot 2020-04-13 at 1 05 pm

**Comment by moewew** [comment]
@plk Oh sorry. Apparently I removed a line I shouldn't have removed in https://github.com/plk/biblatex/commit/95c86f3b52d8f0a2bd3fa3e78a2cd98a55d395ec, should be fixed in https://github.com/plk/biblatex/commit/7bbc2155cce69ba43cef1fdd1d845a38a810d328. Fingers crossed. Thanks for catching that!

**Comment by Skillmon** [comment]
@moewew Very good example:) Just want to point out that the macro `\newcommand*{\blx@kv@undef}[2]{\csundef{\ekv@name{#1}{#2}}}` should've been `\newcommand*{\blx@kv@undef}[2]{\csundef{\ekv@name{#1}{#2}}\csundef{\ekv@name{#1}{#2}N}}` to also clear the default if it was set. Do you intend to provide options to use different key=val implementations without it requiring advanced knowledge from the user (else I don't see much advantage from this generalisation)?

**Comment by moewew** [comment]
Fixed, thank you.

Eventually I was hoping to give users a way to switch more easily, yes. But I haven't really tried to figure out what how we could best do that and it would probably need additional testing of the alternatives. For now this PR mainly makes sure that we understand what we need from a key-val interface and gives us a unified way to use the required features.

**Comment by Skillmon** [comment]
@moewew I'd provide single files for each supported key=val interface (so that new ones can be added easily by pull requests) and a loader-package which gets a single option stating the used key=val package. Something like the following:

```tex
\ProvidesPackage{blxkeyval}
\DeclareOption*{\let\blxkeyval@pkg\CurrentOption}
\ProcessOptions\relax

\IfFileExists{blxkeyval.\blxkeyval@pkg.tex}
  {\input{blxkeyval.\blxkeyval@pkg.tex}}
  {\PackageError{blxkeyval}{Unknown key=val package `\blxkeyval@pkg'}{}}

\endinput
```

Your code above could then be the contents of `blxkeyval.expkv.tex`.

**Comment by plk** [comment]
@moewew - I wonder if you could have a look at biblatex.sty in the multiscript branch - I merged the keyval changes but there are a couple of places where I def raw `KV@` in some deeply nested defs and I'm not sure how to integrate this with the new macros - it is likely more obvious to you if the keyval code is still in your head for a while.

**Comment by moewew** [comment]
I hope https://github.com/plk/biblatex/pull/992 is enough, but I may well have missed something.

**Comment by moewew** [comment]
I didn't expect this change to have impact on contributed styles, but just grepped for `\define@key` in my directory of `biblatex` styles and noticed that `biblatex-philosophy` uses it to add custom options to `\printbibliography`. Maybe we need a real interface for that?

Anyway for now, style authors will want to replace `\define@key` with `\blx@kv@defkey` and `\setkeys` with `\blx@kv@setkeys`. If they want backwards compatibility with older versions of `biblatex` (probably a good idea) they'll probably also want to add
```latex
\providerobustcmd*{\blx@kv@defkey}{\define@key}
\providerobustcmd*{\blx@kv@setkeys}{\setkeys}
```

I think the developer of `biblatex-philosophy` is ivalb on GitHub but just to be sure I got the right person, I'll send an email and avoid `@` mentioning him here.

**Pull request merged**
