### PR TITLE
`nodate` now conforming to the "Règles typo. en usage à l'IN".

### PR DESCRIPTION
**Pull request by dbitouze**

### CODE REVIEW

**Comment by moewew** [comment]
Note that removing the leading `{}` in the short form will lead to the "s" being capitalised as normal. Sometimes this may not be desired (so much so that in some languages this is explicitly suppressed), see
```latex
\documentclass[french]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[style=authoryear, backend=biber]{biblatex}

\DeclareDelimFormat[bib]{nameyeardelim}{\addperiod\space}

\begin{filecontents}{\jobname.bib}
@book{appleby,
  author  = {Humphrey Appleby},
  title   = {On the Importance of the Civil Service},
}
\end{filecontents}
\addbibresource{\jobname.bib}


\begin{document}
\autocite{appleby}
\printbibliography
\end{document}
```

**Comment by dbitouze** [comment]
@moewew OK. I don't know how to proceed: submit a new PR?

**Comment by moewew** [comment]
**If** you want to add the `{}` you can just push another commit to this branch, normally the pull request should then update automatically.

Note that I did not want to say that you need to add the `{}`, I'll have to leave that up to you, because I have no idea about French typographic conventions.

**Comment by dbitouze** [comment]
> Note that I did not want to say that you need to add the `{}`, I'll have to leave that up to you, because I have no idea about French typographic conventions. I just wanted to point out the difference.

You did well: the initial of the short form shouldn't be uppercase.

**Comment by moewew** [comment]
Thanks for checking that and for the new commit.

Merged. Thank you very much.

**Comment by dbitouze** [comment]
You're welcome! :smile:

**Pull request merged**
