### PR TITLE
corrected and translated more strings

### PR DESCRIPTION
**Pull request by kristiank**

### CODE REVIEW

**Comment by moewew** [comment]
Thank you very much. Should we merge this directly or is there more to come?

Do you want to be listed as language contributor in the documentation? In that case we'd need to know how you want to be credited.

**Comment by kristiank** [comment]
There's more to come, maybe wait for a few days. In a later perspective I'd like to ask someone "professional" for more correct terms to use (if any such exists).

I'd could be credited, is there some examples how others has been credited? Basically I'd like my NGO called MTÜ Keeleleek and my name Kristian Kankainen be shown.

**Comment by moewew** [comment]
Normally we only go for the name if that's OK with you. Have a look at §1.4 *Acknowledgements* of the documentation.

If you want to check your localisation, you can use the file [`03-localization-keys.tex`](https://github.com/plk/biblatex/blob/dev/doc/latex/biblatex/examples/03-localization-keys.tex) that comes with your `biblatex` installation.

**Comment by kristiank** [comment]
Only the name is OK (Kristian Kankainen).

**Comment by kristiank** [comment]
My commits could be merged now. I will revise and continue the work when I have visited the library.
Let's leave the `in:` macro until then, although I agree in removing it totally when I know the term "teoses" is appropriate also for articles.

**Comment by moewew** [comment]
Thank you.

A test against `03-` showed that the following strings are missing at the moment

- [ ] organizer
- [ ] organizers
- [ ] byorganizer
- [ ] involumes
- [ ] pagetotal
- [ ] columntotal
- [ ] columntotals
- [ ] sectiontotal
- [ ] sectiontotals
- [ ] paragraphtotal
- [ ] paragraphtotals
- [ ] versetotal
- [ ] versetotals
- [ ] linetotal
- [ ] linetotals
- [ ] circa
- [ ] langjapanese
- [ ] langukrainian
- [ ] fromjapanese
- [ ] fromukrainian

Not all of them may be in the `.lbx` as untranslated strings yet.

`csquotes` also has no quote style for Estonian. So if you know how that should look like you can read https://tex.stackexchange.com/q/166337/35864 and head over to https://github.com/josephwright/csquotes/pulls

**Comment by kristiank** [comment]
Added quote styles for Estonian in `csquotes`. Do you know how fast they usually react and merge?

**Pull request merged**
