### PR TITLE
translated few untranslated finnish phrases

### PR DESCRIPTION
**Pull request by kristiank**
I'm still unsure about correct terminology (if there even exists such a thing), but Estonian phrases is far better than Finnish phrases.

### CODE REVIEW

**Comment by kristiank** [comment]
I will try translate more in due time.

**Comment by moewew** [comment]
Thank you very much for your contribution. If you can find some time, could you comment on

https://github.com/plk/biblatex/blob/45a7dcd128589acdf76f89656ab881d2a00b0d33/tex/latex/biblatex/lbx/estonian.lbx#L77-L81

I don't actually think the language files should redefine the `in:` bibmacro in this way. Even if it is unusual for Estonian to put an "in:" before the journal in for articles.

**Comment by kristiank** [comment]
The macro has been copied from the Finnish file. There are several different ways to format bibliographies in Estonian.
Where do you think these kind of things should be defined if not in the language files?

**Comment by moewew** [comment]
I'd just leave it and let users sort these things out themselves. No other `.lbx` files apart from Finnish does this sort of thing and it leads to inconsistencies and could even overwrite user decisions. So if there is no grammatical/linguistic reason for it, I would really like to get rid of it.

**Comment by kristiank** [comment]
As far as I understand, the macro leaves out the `in:` if the `entrytype` is `article`. Since the `in:` is defined as "teoses" (literally _in the work_). I am not sure if it is propriate or not to use this term for entries of type article.
I am curius how should users sort these things out themselves? I am very new to biblatex and latex in general.

**Comment by moewew** [comment]
A user could use the method discussed in https://tex.stackexchange.com/q/10682/35864 for example.

I have to trust your judgement here. The original localisations of this package are focused on German, English and French. There it is possible, if slightly unusual, to use "in:" for articles as well. Now if "teoses" is an absolute no-go for `@article`s in Estonian and not just a bit unusual (as it is in almost all languages), we would have to think about that.

I am a bit sceptical of `.lbx` files redefining bibliography macros. That can have unintended or unusual consequences in certain edge cases. And in this case it makes things inconsistent between Estonian and Finnish and all the other languages. That's why I'm concerned with the `in:`.

**Comment by sim642** [comment]
@moewew I strongly believe that "in:" hack should not be part of the language. Whilst the simple approach to get rid of "in:" altogether is to override the bibliography string, this hack in the estonian language makes that impossible. One has to resort to messing around with the bibliography macro instead. `@article` to me seems in no way special than other types, which usually don't need "in:" either. This hack just makes using the estonian language more difficult by requiring completely not obvious workarounds which are not required in any other language.

I agree that it should be left to the end user to do something like that themselves if really desired. Seems like someone has just submitted their personal stuff into the repository which doesn't necessarily suit everyone else.

**Comment by moewew** [comment]
@sim642 Thank you for weighing in here.

My feeling is also that an `.lbx` files should rather not modify bibmacros. But as it turns out the localisation system and the way it is used in some macros make it hard to satisfy the needs of certain languages. The system was written from an English/German/French background and simply has no interface for some concepts of other languages. Particularly troubling are for example changes in the word order and use of declension. Especially the latter can mean that certain strings have no sensible translation as a single word, but should rather be realised by other means (say, by declining the following phrase). The localisation framework has no support for declension of field contents and also has troubles with empty string translations (they may appear to work, but can break in certain situations since parts of the code were written assuming that `\bibstring{<string>}` always has a non-empty output).

This means that suppressing the output of a string by redefining it to be empty is problematic and should be avoided. If it is to be avoided, the next best solution is to redefine the field formats and macros that use that string. But that has the counter-intuitive effect that these formats and macros can now only be modified by a user or style in an `\DefineBibliographyExtras`. We had to take a route like this for Hungarian, see https://github.com/plk/biblatex/issues/717.

As an aside: Another problem is that `.lbx` files are not just about translation. To a limited degree they also venture into the realms of style. Take `french.lbx` as an example, it changes the format of family names to small caps. Apparently that is such an integral part of French typographic traditions that it was felt that the `.lbx` should apply this definition. In German on the contrary, small caps are not entirely unusual or unheard of, but it would be a stylistic choice whether or not to use small caps for family names and imposing small caps on users by default would probably be seen as wrong.

For the record and for other people reading this. Assuming the aim is to get rid of "in" for all entry types, overriding the bibliography **string** `in` still works (but it is not something I would recommend at all since it can lead to problems with punctuation, try `\renewcommand*{\intitlepunct}{XX}\DefineBibliographyStrings{estonian}{in={}}`). What does not work immediately is modification of the bibliography **macro** `in:` (this is my preferred solution), it has to happen in an `\DefineBibliographyExtras{estonian}` (i.e. `\DefineBibliographyExtras{estonian}{\renewbibmacro*{in:}{}}`). This is not immediately obvious from the start and contrary to the behaviour of almost all other languages.

Anyway, I'm open for suggestions to improve the situation that do not require a rewrite of the entire localisation system.

**Comment by josephwright** [comment]
@moewew All sounds reasonable to me (though I'm always a bit disappointed when style leaks into language settings: it's a long-standing issue and not `biblatex`'s fault).

**Pull request merged**
