### PR TITLE
Added romanian.lbx

### PR DESCRIPTION
**Pull request by mafsi**
# Checklist for submitting `romanian.lbx` file

## Encoding

> `.lbx` files must be encoded in ASCII (using TeX commands for accents if required) or UTF-8. If possible, ASCII is preferable because any ASCII file is also a valid UTF-8 file, making the `.lbx` file more versatile.

`romanian.lbx` is encoded in UTF-8. ASCII doesn't display characters `Ș ș`, `Ț ț` 

## Bibliography Strings
1. Copy the existing file and rename it. Use the `babel` language identifier of the language as the file name.
   - Done! used `english.lbx` as template. 
2. Remove the `\DeclareBibliographyExtras` and `\UndeclareBibliographyExtras` parts (for the time being, see below for explanation).
   - Done! 
4. Translate the `\DeclareBibliographyStrings` part. Note the following: 
      * When using `english.lbx` as a template, remove the `\finalandcomma` macros from the translations. This is only required to support both British and American English in one file. Other modules should either place or omit a comma, depending on the language.
        - Done!  
      * Abbreviated strings must use `\adddot` or `.\isdot` at the end of the string because Biblatex's punctuation tracker distinguishes periods and abbreviation dots.
        - Done! Used `\adddot`  

## Bibliography Extras

Adding bibliography extras requires more in-depth knowledge of Biblatex's localization modules. It is usually best if you go over the checklist below and send the answers to the Biblatex developers along with the translations; i.e., you translate the `\DeclareBibliographyStrings` part but omit `\DeclareBibliographyExtras`. 

  1. What kind of dash do you use in number ranges like "35-50"? 
      * romanian language use `\textendash` 
      * Are there any spaces around the dash?
        - no spaces 
  2. What kind of dash do you use in date ranges like "1st January-3rd February 2009"? 
      * romanian language use `\textendash` 
      * Are there any spaces around the dash?
        - there are spaces   
  3. In lists and enumerations, do you add a comma in addition to connectors like "and"? 
      * no comma. We use UK English: "apples, oranges<b> and </b>cherries"
     
  4. How do you format short ordinals? Are ordinals gender/number sensitive? Examples: 
      * in Romanian short ordinals are gender sensitive except `1` which is cardinal gender insensitive:
      
          | masculin/neutre | feminin |
          |:---------------:|:-------:|
          |    al (-lea)    | a (-a)  |

        Examples: 
         - `(feminin) Ediția (eng. Edition) a 2-a, a 5-a, a 11-a, a 121-a`
         - `(neutre) Volumul (eng. Volume) al 2-lea, al 5-lea, al 11-lea, al 121-lea`
         -  `a 2[hyphen]a`; `al 11[hyphen]lea`
        
        Please take in account (if necessary) the order because there are differences between publishing houses. In examples above `Ediția` and `Volumul` are with article; ***if the order is changed we use without article***:
        `a 2-a Ediție`, `a 5-a Ediție` ; `al 2-lea Volum`, `al 11-lea Volum` etc.
                   
  5. What's the gender of the word "edition"?
     - `s.f` nominative   
  6. What's the gender of the word "series" (of a journal)?
     - `s.f` `pl.` : `Serii`
     - example: `Seria 1` (s.f., sg., `+ article`, cardinal gender insensitive); `Seria a 2-a` (s.f, sg., gender sensitive)
  7. What's the long date format?
     - long version: `[day as cardinal][month name][year]`: `19 Decembrie 2020`
     - abbrev. version: `[day as cardinal][short month name][year]`: `19 Dec. 2020`
     1. What happens if the day is missing from the date?
        - `Decembrie 2020`
     2. What happens if both day and month are missing?
        - `2020` 
     3. Does this day format use leading zeros?
        - `no leading zeros` 
     4. Please be specific about the spaces to be used (non-breakable, thin spaces).
        - `non-breakable space for date` 
     5. What happens for date ranges with compact (1.--6. February 2010, 1. February--6. March 2010) and non-compact ranges (1. February 2010--6. February 2010)?
        - `1[\textendash]6[space]February[space]2020`
        - 1 Februarie`[space][\textendash][space]`6 Martie 2010

  8. What's the short date format?
     - `18.12.2020 [day][month][year]`
     2. What happens if the day is missing from the date?
        -  `Dec\adddot\ 2020`  (Dec. 2020); **if day is missing we don't use 12.2020, we abbreviate: Dec. 2020**
     3. What happens if both day and month are missing?
        - `2020` [year]
     4. Does this day format use leading zeros?
        - `no leading zeros`
     5. Please be specific about the spaces to be used (non-breakable, thin spaces).
        - `non-breakable space`: `Dec. 2020`; **at the end of the line we don't breake date**
     6. What happens for date ranges with compact (1.--6. February 2010, 1. February--6. March 2010) and non-compact ranges (1. February 2010--6. February 2010)?
        - `1-6 Feb. 2020`; [day range with \textendash][space][month abbreviated][space][year]
        - `1 Feb. - 6 Mar. 2020` [day][space][month abbreviated][space][\textendash][space][day][space][month abbreviated][year]
        - we don't use: `1-6.02.2020` or `1.02 - 6.03.2020`

  9.  After which punctuation marks do you capitalize a word? Examples: 
       - `after ". ! ?" (English = package default)`
  10.  What's the 12h time format?/What's the 24h time format?
       - `07:43 a.m./p.m.` or `7:43 a.m./p.m.` as 12h time format
       - `19:43` as 24h time format   
  11. What's the format for dates with seasons only, such as 'Summer 2010'?
      - `Primăvara 2020` -> Spring 2020   

## Testing
1. I have noticed that in References is used `dot ` after Author. We don't use dot, but comma

**Example in Reference no.2:**

Arnold Angenendt. ?In Honore Salvatoris – Vom Sinn und Unsinn der Patrozinienkunde? În: Revue d’Histoire Ecclésiastique 97 (2002), pp. 431–456, 791–823.

**should be**

Arnold Angenendt`[comma]` `[space]` `[\quotedblbase]`In Honore Salvatoris – Vom Sinn und Unsinn der Patrozinienkunde`[\textquotedblright]` `[space]` `[în]` `[space]` *Revue d’Histoire Ecclésiastique* 97 (2002),
pp. 431–456, 791–823. (see below)

Arnold Angenendt, „In Honore Salvatoris – Vom Sinn und Unsinn der Patrozinienkunde” în *Revue d’Histoire Ecclésiastique* 97 (2002), pp. 431–456, 791–823.

**also ref. no. 38 should be**

Philipp Jaffé, `(Ed.)` *Regesta Pontificum Romanorum ab condita ecclesia ad annum post Christum natum mcxcviii*`,` Red. de Samuel Loewenfeld, Ferdinand Kaltenbrunner și Paul Ewald`,` `a 2-a Ed.` /or/ `Ed. a 2-a` `,`  2 vol.`,` Leipzig, 1885–1888.

**ref. no. 48**
before:
[48] Solomon Kullback. Information Theory and Statistics. New York:
John Wiley & Sons, 1959.

after:
[48] Solomon Kullback`comma` *Information Theory and Statistics*`comma` New York`comma`
John Wiley & Sons, 1959.

## Other
Please help me to have in references: `[\quotedblbase]` Article name here `[\textquotedblright]` ... etc

### CODE REVIEW

**Comment by moewew** [comment]
Thank you very much.

I will have a closer look at the bibliography extras later.

For now let me just say that you see question marks instead of quotation marks because `csquotes` doesn't support Romanian. So you may want to drop by https://github.com/josephwright/csquotes/issues and offer your help with Romanian there. (A typical commit to add a new language to `csquotes` would look like https://github.com/josephwright/csquotes/pull/23.) I'd say the period between fields in the bibliography (instead of a comma) is a style decision that should not depend on the language. Unless a period is absolutely unacceptable in Romanian I would rather not change it, since it would make for a worse user experience if users want to change it. (There is a similar discussion for the Marathi localisation that is currently being worked on, see https://github.com/plk/biblatex/pull/1060#issuecomment-739661210, where I explain my reasoning in more detail).

**Comment by mafsi** [comment]
Hi,
Thanks a lot for your help!

I read your comment on marathi localization.

## The problem of In: `În:` vs. `în:` vs `în`

1. We don't capitalize first letter inside a sentence, but I assume this will be fixed since I answered on the questions that we use capitalization `after ". ! ?" (English = package default)`

2. colon punctuation. We normally don't use colon after preposition `în` in bibliography, but let's say that there is an argument in Romanian grammar for use it: colon can be use before a citation in Romanian. So we can assume that the Periodic Title is in fact a citation of a title.

## The problem of `dot` vs. `comma` in Bibliography

I understand that Biblatex use dot to delimit some strings and somehow the dot is used by many international styles so it was a win-win situation.

### The Romanian case
Although we don't have an official citation manual, we use to major styles in academic references: APA & Chicago, but when is about Bibliography we don't we dot. This choice is not about style, is according to our grammar: In Romanian every bibliographic extras is considered a long enumeration of items and those items are comma delimited. Use only use dot (period) at the end of a sentence. This is the only case we use dot. Sometimes we use in titles: Article. Adjective. Substantive. ; in this case is more a matter of style to show in title some chapters since we can say: Article, adjective and substantive

#### The problem of inconsistency of a document when redefining commands

I didn't understand very clear this aspect since I'm newbie in LaTeX. But here are some aspects and please tell me if these are addressing the problem you mentioned.

1. In Romanian language either in Academic papers or in Books published we use comma in bibliography no matter the book is in English, Marathi, French etc. Always!
2. When we have to publish an article, book etc in other language we give credit to that language and we use all the specification of that country. Therefore: if I want to publish an article or a book in Romania I will be forced to use comma in bibliographics extras. If I want to publish an article in english I'll load in LaTeX that specification: \usepackage[english]{babel} and I don't care how Bibliography is looks like since I will use that particular country specification.

**Comment by moewew** [comment]
Sorry that my writing in the Marathi thread (and here) was unclear. The point I'm trying to make is that I don't want the `.lbx` files to make *style* decisions that move against the standard styles. So style elements should only be changed if that is required for *orthographic correctness*.

The thing is that these changes create an inconsistent output across languages and make for an inconsistent user experience if users want to change these style aspects. So I want to avoid *stylistic* changes. Obviously correctness is more important, so if there is no way a period would be acceptable in Romanian, we can and will change the period to a comma in the Romanian `.lbx` file.

Please have a look at [03-localization-keys.pdf](https://github.com/plk/biblatex/files/5728502/03-localization-keys.pdf) and tell me what you think.

Currently I'm using the following quotation mark settings for Romanian
```latex
\documentclass[romanian]{article}
\usepackage[T1]{fontenc}
\usepackage{babel}
\usepackage{csquotes}

\DeclareQuoteStyle{romanian}
  {\quotedblbase}
  {\textquotedblright}
  {\guillemotleft}
  {\guillemotright}

\begin{document}
Lorem \enquote{ipsum \enquote{dolor} sit} amet

Lorem \enquote{\enquote{ipsum dolor} sit} amet

Lorem \enquote{ipsum \enquote{dolor sit}} amet
\end{document}
```
Lorem „ipsum «dolor» sit” amet//Lorem „«ipsum dolor» sit” amet//Lorem „ipsum «dolor sit»” amet
if that looks right to you, you may want to submit a pull request to `csquotes` with those settings (cf. https://github.com/josephwright/csquotes/pull/23).

**Comment by mafsi** [comment]
> Please have a look at [03-localization-keys.pdf](https://github.com/plk/biblatex/files/5728502/03-localization-keys.pdf) and tell me what you think.

**Amazing work, @moewew !**

I was about to push the same csquotes and make a PR.

### A few questions about Bibliography

It seems that I made small mistakes.

---

1st ed

1. We write either `Prima` Ediție, or Ediția `I`. As for `1-a` ediție I have to confess I never saw it in a Bibliography. I saw only Ediția I and Prima Ediție. 
2. Please put `1-a` as ordinal, because seeing it now in a Bibliography is ok. Also, please make changes accordingly to masculin and neuter i.e. `1-ul vol. / Volum`

---

number

Between `ser.` and `15` should't be `no.`? (Număr) (Nr.) (nr.) in Romanian?

---

ser_noua

between `ser.` and `nouă` we need space.

_Please except my apologize for those mistakes!_

**Comment by moewew** [comment]
I've changed the ordinal for 1 to "a 1-a" etc.

`biblatex` currently does not use ordinals for volumes, it uses cardinals. The order is "Volume 5" and not "5th volume". If that's not acceptable in Romanian, we can change that.

Re [68] There is no "nr." or "vol." in the English version of the reference either. The "3rd. series" refers to the journal title, the 15 is the normal `volume` number that has no introductory string.


Current state [03-localization-keys.pdf](https://github.com/plk/biblatex/files/5731089/03-localization-keys.pdf)

**Comment by mafsi** [comment]
> The order is "Volume 5"

It is acceptable.

Please take a look at reference no. 31. `1-a ed.` not `a 1-a ed.` , in Romanian language no. 1 doesn't have `a` in front. 

Examples:

`1-a ed.`
`a 2-a ed. .... a 99-a ed. ... a 101-a ed. ...a 1234567-a ed.`

I didn't spot any other problems.
**Thanks a lot for your help**!. After the update is included I can write my PhD in LaTeX. 
https://tex.stackexchange.com/questions/574351/footnote-display-problem-using-romanian-babel-chicago-style

**Comment by mafsi** [comment]
Ready to be merged if is ok with you.

**Comment by moewew** [comment]
I'll have to work on some of the date formatting, so it will probably be a few days before we can merge, sorry.

Usually we credit language contributors in the documentation. Do you want to be credited there as well? If so, what name would you like to see in the docs?

**Comment by mafsi** [comment]
@moewew , sure you can credit me.
`Patrick Danilevici` is my name. 
I'll leave the fork there and I'll keep maintaining if new strings will appear.

**Comment by moewew** [comment]
Thank you very much. The PR was manually merged in https://github.com/plk/biblatex/commit/d5fea521f13a9143ec7299b6bd24926ebb87ab4c and https://github.com/plk/biblatex/commit/9a0a794d48f5e676756ace56530c00c5f3016174. You can grab the current state from `dev` and give it a spin.

**Pull request closed without merging**
