### PR TITLE
L3build

### PR DESCRIPTION
**Pull request by josephwright**
This PR enables `l3build` for testing, etc. At present, GitHub Actions is set up only for testing, as the documentation typesetting needs a system font.

The current tests are simply the examples turned into `.lvt` files. I would suggest that longer-term new tests could be separated out

- Ones that do one LaTeX run and create the `.bcf`/`.aux`, which can then be verified
- Ones that do one or more LaTeX runs and read the `.bbl` file, which can then be tested using `\showoutput`

An approach avoiding running Biber would be faster and would be purely focussed on the LaTeX code.

Running the CTAN target requires manual setting of the `biblatex` version first:
```
l3build tag <version> && l3build ctan
```
I will look at extending `l3build` to deal with that more cleanly once I know that other areas are usable. In particular, I could do with some input on exactly which files go where and whether any rearrangement of the sources would be permitted to help that.

### CODE REVIEW

**Comment by josephwright** [comment]
BTW, this would (finally) close https://github.com/plk/biblatex/issues/374 I think

**Comment by josephwright** [comment]
I've not included the dev Biber aspect: that is workable (just have to install in the right place), but at the moment I get test failures that suggest I've got a mismatched Biber/`biblatex`, so I thought that should be handled separately.

**Comment by josephwright** [comment]
I've got a version sorted that works on the dev branch: would you prefer I rebase to 'offer' that one here?

**Comment by moewew** [comment]
Yeah, it would be great to have this work properly on `dev`.

**Comment by josephwright** [comment]
Infrastructure updated: a few test results change as a result and will follow shortly

**Comment by josephwright** [comment]
All working now: I guess I could add `biber` to the cache, but that seems overkill.

Looking forward to hearing what changes are needed :)

**Pull request merged**
