### PR TITLE
russian.lbx update

### PR DESCRIPTION
**Pull request by odomanov**
I also added bibstrings for Japanese. Could you add their support to `biblatex`?

### CODE REVIEW

**Comment by plk** [comment]
Manually merged into biblatex dev branch, thanks.

**Comment by odomanov** [comment]
Probably you didn't add the support for Japanese (am I right that this should be done in biblatex?). 
I've got the following compilation error with biblatex 3.1 and 3.2:

````
(c:/texlive/texmf-local/tex/latex/biblatex/lbx/russian.lbx
File: russian.lbx 2015/11/02 v3.2 biblatex localization (PK/JW/AB)


! Package xkeyval Error: `langjapanese' undefined in families `blx@lbx'.
```

**Comment by plk** [comment]
Ah, yes, sorry. Please try 3.2 from SF again

**Comment by odomanov** [comment]
Sorry :) There is another string --- `fromjapanese`.

**Comment by plk** [comment]
Sorry - please pull 3.2 again.

**Comment by odomanov** [comment]
SF probably hasn't updated yet, but the repo version works fine. Thanx.

**Pull request closed without merging**
