### PR TITLE
Drop xstring

### PR DESCRIPTION
**Pull request by moewew**
Following https://github.com/plk/biblatex/pull/813 I investigated whether it would be possible to drop `xstring` altogether. It turned out that `biblatex` was only using very few commands in very specific places and that it was possible to come up with more primitive replacements there.

It also turned out that `pdftexcmds` was only used in one macro and that that could also be replaced with `etoolbox` macros.

This is more of a code aesthetic suggestion rather than one that resolves unwanted behaviour. So I'd like to discuss this first before merging.

Currently at least the following styles use `xstring` macros
- [ ] biblatex-abnt (https://github.com/abntex/biblatex-abnt/issues)
- [x] biblatex-archaeology (https://github.com/CarlOrff/biblatex-archaeology/issues)
- [x] biblatex-bath (https://github.com/alex-ball/bathbib/issues)
- [ ] biblatex-gb7714-2015 (loads `xstring`, but with a comment that suggests that this is only done to support older versions) (https://github.com/hushidong/biblatex-gb7714-2015/issues)
- [x] biblatex-oxref (loads `xstring`) (https://github.com/alex-ball/biblatex-oxref/issues)
- [x] biblatex-true-citepages-omit (loads `xstring`)
- [x] biblatex-swiss-legal (loads `xstring`)

If we decide not to load that package any more we would probably have to notify the package authors to explicitly load `xstring` themselves.

What do you think?

### CODE REVIEW

**Comment by josephwright** [comment]
Looks like a good plan!

**Comment by moewew** [comment]
@josephwright Cool. Comments on the quality of my suggested replacements and corrections or other suggestions are very welcome.

**Comment by josephwright** [comment]
The replacement for `\pdf@strcmp` is fine provided there's no need for expandable code. I'll check the string decomposition ones.

**Comment by moewew** [comment]
If we want to merge https://github.com/plk/biblatex/compare/dev...moewew:hashlpm for #738 we need to keep `pdftexcmd` for `\pdf@mdfivesum`. With `pdftexcmd` back in the play we could resurrect `\blx@xifstrcmp` in its previous form. I don't really see the point, because `\blx@xifstrcmp` is used only in very specific situations and need not be expandable, but I'm open for a discussion.

`xstring` can still go, though. @josephwright Did you find any obvious blunders in my poor man's `xstring` replacements?

**Comment by moewew** [comment]
@plk Can we get this into 3.12?

**Comment by plk** [comment]
Yes, just push it and I'll re-upload. I only count it as a "release" when it hits CTAN and I won't push that until the biber binaries are all ready which will be a week or so.

**Comment by moewew** [comment]
Ah OK. Very good.

I'll send out another announcement to c.t.t. Not that anyone got back to us after the last one, but you never know.

**Pull request merged**
