### PR TITLE
Revamp .lbx loading

### LINKED ISSUE #677: british gives different (and wrong) short date format compared with UKenglish with polyglossia
The following MWE example gives a URL date of 10/01/2006 (mm/dd/yyyy). But if I substitute `UKenglish` for `british` in the language mapping, it correctly gives 01/10/2006 (dd/mm/yyyy). This appears to only be a problem with `polyglossia`. Both `[british]{babel}` and `[UKenglish]{babel}` give the same output.

```TeX
\documentclass{article}
\usepackage{polyglossia}
\setdefaultlanguage[variant=british]{english}
\usepackage[urldate=short]{biblatex}
\DeclareLanguageMapping{english}{british}
\addbibresource{biblatex-examples.bib}
\pagestyle{empty}
\begin{document}
\nocite{ctan}
\printbibliography
\end{document}
```

### PR DESCRIPTION
**Pull request by moewew**
Revamp loading of `.lbx` files.

Solves #677, #696. Ping back to #612, #525.

The changes are to critical infrastructure, so they need close scrutiny. The incompatible change is unlikely to cause any problems for existing `.lbx` files provided they are used as described in the docs.

Comments and testing are very welcome. I would like to wait a bit before merging this pull request. If nothing serious comes up I will merge in a few days.

### CODE REVIEW

**Comment by plk** [comment]
This looks nice - much better than the hack I put in for recursion originally and the separation of elements in lbx files is nice.

**Comment by moewew** [comment]
Have merged this, since I could not find any problems in my tests.
Once we have merged #704 (with the necessary modifications) if any, could you please upload a new dev version to Sourceforge. I'm planning on inviting people on comp.text.tex to test.

**Comment by plk** [comment]
@moewew - Will do. Can you mail me your real name as I think you ought to be listed as a developer now since you are doing so much. The other two names listed rarely contribute any more.

**Comment by moewew** [comment]
Since the name will be listed anyway I might as well give it here: Moritz Wemheuer

If you could have a look at #704 and in particular the new name of the delimiter `begrelateddelim`, I'd really appreciated it.

**Comment by plk** [comment]
Everything merge and tests are ok - new 3.11 DEV is uploaded.

**Comment by moewew** [comment]
Thank you very much.

**Comment by moewew** [comment]
The call for testing in c.t.t didn't produce a huge echo (it did spark a discussion about the merits of usenet, GitHub and Stackexchange, though). Joseph did a few basic test that went alright. I asked a few other people directly who could not find any immediate problems either. So I'm hoping we are good.

If #705 needs no further intervention, I would only need to think #707 (of course I would appreciate your input there as well). Then I would like to start the release sequence for 3.11 on the weekend. If we only freeze `biblatex` 3.11 once Biber 2.11 is built, we might have another days or two in case something comes up. We could then upload to CTAN at the beginning of next week. If something goes horribly wrong once 3.11 is out we might have to react quickly with a 3.11a.

**Pull request merged**
