### PR TITLE
Update danish.lbx

### PR DESCRIPTION
**Pull request by Hen-Rex**
Fixed some double periods, e.g. adding both a period and a \adddot.
Fixed double spacing due to too many blackslashes, such as \space\ and \adddotspace\\
Fixed incorrect or outmoded translations
Added missing translations marked as "FIXME".

### CODE REVIEW

**Comment by plk** [comment]
Merge -  very good, thank you. The situation where a localisation string is in the APA `.lbx` and also in the `biblatex` standard `.lbx` should only occur when the APA string is different from the default `biblatex` string. There are situations like that in english and for other languages, I have to rely on the APA-like practices of other languages that are submitted by contributors familiar with the language.

**Review by Hen-Rex — COMMENTED** [review]
Changed capitalisation errors in bathesis, mathesis, candthesis and phdthesis.

**Comment by moewew** [comment]
Is there a specific reason why there are now curly braces around `\ae`, `\aa` and `\o`? I expected those not to be necessary. In `.bib` files compiled with BibTeX the braces are needed in order to get "correct" sorting. But in normal text I don't think they are useful. In fact they might stop kerning from working as expected (though I must admit I don't know if `\ae`, `\aa`, `\o` have any kerning info at all, especially when they are macros)

**Comment by Hen-Rex** [comment]
It's just the way we usually do it with the letters æ ø å. And also `redakt{\o}r` is more legible and less prone to spelling errors than `redakt\o er` in my opinion. I tested it and compiling works fine. I did not test if bolded, italics, etc. works as intended though it is pretty standard to format it this way with the special three Danish letters.

**Pull request merged**
