### PR TITLE
Introduce option to automatically use sequens, sequentes in postnote (#217)

### PR DESCRIPTION
**Pull request by jspitz**
This entails new formatting commands `\mkseqrange[*]` and `\mkseqornormrange[*]` as well as a new option
`pageseq=none|two+|three+|all+`

The lexic of the latter is adapted from `backrefstyle`.

### CODE REVIEW

**Comment by jspitz** [comment]
An afterthought: We could also generalize the option a bit more to provide even more convenience:
* rename proposed macro `\mkseqornormrange` => `\mkautorange`
* make it also consider `\mkcomprange`
* rename proposed option `pageseq` => `citepagerange` with values `normalized` (default), `compressed`, `2sq`, `3sqq`, `allsqq`

I think this would be a useful interface. What do you think?

**Comment by jspitz** [comment]
I have updated my pull request to include the extensions proposed in https://github.com/plk/biblatex/pull/1392#issuecomment-2453305335

**Comment by jspitz** [comment]
BTW as far as I can see the reason for the checks failing is a biblatex/biber version mismatch in `dev` branch.

**Comment by moewew** [comment]
Looks nice. Thank you *very* much. I'd like to squash and merge to keep the history a bit nicer. Would that mess things up hugely on your end?

**Comment by jspitz** [comment]
I think I can deal with it. It's better for me to do a completely new fork after this has been merged anyway in order to start from a clean history.

**Comment by moewew** [comment]
Nice. Merged.

(I guess it is probably easier to work on feature branches in future, then you don't need to worry too much about what's going on on `dev`.)

**Pull request merged**
