### PR TITLE
Add Serbian and Turkish strings to Brazilian

### PR DESCRIPTION
**Pull request by gusbrs**
Provides new strings values to brazilian.lbx.

### CODE REVIEW

**Comment by moewew** [comment]
Thank you very much. Merged.

Can you also tell me the translations for
- `langlithuanian`
- `fromlithuanian`

Following https://github.com/plk/biblatex/issues/972 `lithuanian.lbx` will hopefully be added to `biblatex` soon.

**Comment by gusbrs** [comment]
Thank you.

As to Lithuanian, I had seen the discussion, but was afraid to add them as I didn't find those strings yet in `\abx@dostrings` in `biblitex.sty`. That given, would you like another PR on that (fine for me) or the strings in a comment here?

**Comment by moewew** [comment]
Ah well, yes I realised that this could be a problem after I added the Lithuanian strings for Turkish in https://github.com/plk/biblatex/commit/c8859131ce11c0a08d72260d8d4840aeeb577f11, but then I thought it more likely that I would forget to ask about the strings again when they are needed than that someone runs into difficulties with the undefined strings.

If it's on your radar I'm extremely happy to wait for your pull request once the Lithuanian branch is merged: Less work for me.

**Comment by gusbrs** [comment]
Oh, yes, it's "in my radar": I watch the repo.   ;-)

And I left it scheduled here, so I won't forget. The PR will come in due time. Besides, I've offered this before, whenever there's need for extra strings for `brazilian.lbx`, feel free to ping me.

**Pull request merged**
